### ISSUE TITLE
phaser flashing

### ISSUE THREAD

**Issue by hartytp** [quartiq/kasli-i2c#2]
what's the status of phaser flashing here? The code looks to be implemented (although missing a nice CLI, but that's easy to add) but this `with False` makes it look like the codepath can never be reached unless I'm missing something? https://github.com/quartiq/kasli-i2c/blob/8dc751a30e8206a9ba06905850145699d1a09ef0/flash_phaser.py#L107

**Comment by hartytp** [comment]
looks like re loading should work as is, which is what we primarily want right now, so will give that a go...

**Comment by pathfinder49** [comment]
@hartytp have you got this working? There are issues with my JTAG adapter, so I'm looking at using this to flash phaser. However, I'm confused to the appropriate arguments for `flash_phaser.py`. Running `python flash_phaser.py kasli_126 EEM0 read test.bin` returns an error (`pyftdi.i2c.I2cNackError: [Errno Address Write NACK] 112`). Where for my kasli v1.1 `ser=kasli_126`.  `EEM0` is the EEM phaser is attached to.

**Comment by hartytp** [comment]
yes, it works on our fork of this tool. let's discuss on slack
