### ISSUE TITLE
BitMode is now an enum in pyftdi

### ISSUE THREAD

**Issue by hartytp** [quartiq/kasli-i2c#3]
Since https://github.com/eblot/pyftdi/commit/5d4be11ed8c22a5c0474ef797d08978a869ae86b#diff-59506818c26b3ffbf38ab767bc9a080c528daee33643289110907e757fa60df1

This means that `kasli-i2c` no longer runs on the current version of pyftdi that ships from conda-forge. Should we update this tool to match the latest?

**Comment by jordens** [comment]
Sure. PR welcome.

**Comment by hartytp** [comment]
:+1: will do. I figured I'd check first in case there was something in your workflow that would prevent a PR being merged.
