### ISSUE TITLE
Fastino configuration issue

### ISSUE THREAD

**Issue by jmatyas** [quartiq/kasli-i2c#8]
I guess I found the reason why the FPGA couldn't load its configuration from flash when reset (see the no CDONE issue https://github.com/sinara-hw/Fastino/issues/48#issuecomment-578191644)

The lines below need to be swapped - according to the [expander datasheet](https://www.nxp.com/docs/en/data-sheet/SC18IS602B.pdf) (p. 9) after the enable command is sent, the GPIO ports are configured as quasi-bidirectional, so when the creload function is invoked the CDONE pin is strongly driven low so the FPGA is not able to finish its configuration.

https://github.com/quartiq/kasli-i2c/blob/e5a1933351887f5ab54368cc0bff6fe9428351f7/flash_fastino.py#L24-L25

**Comment by jordens** [comment]
Ack. Could you make a pull request?

**Comment by jmatyas** [comment]
Sure, I will do it today

**Comment by jordens** [comment]
@jmatyas ping

**Comment by jmatyas** [comment]
Done, sorry for long waiting time
